name: nuclei_analysis_2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - absl-py=2.1.0
  - aom=3.9.1
  - astunparse=1.6.3
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.3
  - c-blosc2=2.15.2
  - ca-certificates=2024.8.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.8.30
  - cffi=1.17.1
  - charls=2.4.2
  - charset-normalizer=3.4.0
  - colorama=0.4.6
  - contourpy=1.3.1
  - csbdeep=0.8.1
  - cycler=0.12.1
  - dav1d=1.2.1
  - flatbuffers=24.3.25
  - fonttools=4.55.1
  - freetype=2.12.1
  - gast=0.6.0
  - giflib=5.2.2
  - google-pasta=0.2.0
  - grpcio=1.65.5
  - h2=4.1.0
  - h5py=3.12.1
  - hdf5=1.14.3
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - imagecodecs=2024.9.22
  - imageio=2.36.1
  - importlib-metadata=8.5.0
  - jxrlib=1.1
  - keras=3.7.0
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libavif16=1.1.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.10.1
  - libcxx=19.1.5
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libgrpc=1.65.5
  - libhwy=1.1.0
  - libjpeg-turbo=3.0.0
  - libjxl=0.11.1
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - liblzma=5.6.3
  - liblzma-devel=5.6.3
  - libnghttp2=1.64.0
  - libopenblas=0.3.28
  - libpng=1.6.44
  - libprotobuf=5.27.5
  - libre2-11=2024.07.02
  - libsqlite=3.47.0
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - llvm-openmp=19.1.4
  - llvmlite=0.43.0
  - lz4-c=1.9.4
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-base=3.9.3
  - mdurl=0.1.2
  - ml_dtypes=0.4.0
  - munkres=1.1.4
  - namex=0.0.8
  - ncurses=6.5
  - networkx=3.4.2
  - numba=0.60.0
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.4.0
  - opt_einsum=3.4.0
  - optree=0.12.1
  - packaging=24.2
  - pillow=11.0.0
  - pip=24.3.1
  - protobuf=5.27.5
  - pthread-stubs=0.4
  - pycparser=2.22
  - pygments=2.18.0
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.11.0
  - python-dateutil=2.9.0.post0
  - python-flatbuffers=24.3.25
  - python_abi=3.11
  - pywavelets=1.7.0
  - qhull=2020.2
  - rav1e=0.6.6
  - re2=2024.07.02
  - readline=8.2
  - requests=2.32.3
  - rich=13.9.4
  - scikit-image=0.24.0
  - scipy=1.14.1
  - setuptools=75.6.0
  - six=1.16.0
  - snappy=1.2.1
  - stardist=0.9.0
  - svt-av1=2.3.0
  - tensorboard=2.17.1
  - tensorboard-data-server=0.7.0
  - tensorflow=2.17.0
  - tensorflow-base=2.17.0
  - tensorflow-estimator=2.17.0
  - termcolor=2.5.0
  - tifffile=2024.9.20
  - tk=8.6.13
  - tqdm=4.67.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - werkzeug=3.1.3
  - wheel=0.45.1
  - wrapt=1.17.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xz=5.6.3
  - xz-gpl-tools=5.6.3
  - xz-tools=5.6.3
  - zfp=1.0.1
  - zipp=3.21.0
  - zlib-ng=2.2.2
  - zstandard=0.23.0
  - zstd=1.5.6
