name: uma_original
channels:
  - conda-forge
dependencies:
  - python=3.10.*        # test on 3.10.15
  - openjdk=17           # PyImageJ / Fiji
  # --- key dependencies ---
  - pyimagej=1.5.0
  - pandas=2.2.*
  - openpyxl=3.1.*
  - scyjava=1.10.0       

