name: uma_original
channels:
  - conda-forge
dependencies:
  # core runtime
  - python=3.10.*          # tested on 3.10.15
  - openjdk=17

  # key ImageJ bridge
  - pyimagej=1.5.0
  - scyjava=1.10.0

  # data analysis & Excel export
  - pandas=2.2.*
  - openpyxl=3.1.*

  # exact plotting backend
  - matplotlib=3.9      
