[build-system]
requires = ["setuptools>=68,<81", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "uma-tools"
version = "0.2.3"
description = "Automated, headless workflows for fibroblast/ECM unit confocal data"
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = [
    "matplotlib>=3.10.5,<3.11",
    "numpy==1.26.4",
    "orientationpy==0.3.0",
    "pandas>=2.1.0,<3",
    "pyimagej==1.5.0",
    "scikit-image==0.25.2",
    "scipy>=1.11.4,<1.16",
    "numba>=0.61,<0.62",
    "scyjava==1.10.0",
    "setuptools<81",
    "jgo==1.0.4",
]

[tool.setuptools]
packages = ["uma_tools"]

[tool.setuptools.package-dir]
uma_tools = "code"

[project.scripts]
uma_alignment = "uma_tools.cli:alignment"
uma_thickness = "uma_tools.cli:thickness"
area_analysis = "uma_tools.cli:area"
