name: orientation_analysis
channels:
  - conda-forge
dependencies:
  - python=3.8
  - openjdk=17
  - maven=3.9
  - numpy=1.24
  - pandas=2.0
  - scipy=1.10
  - scikit-image=0.21
  - matplotlib=3.7
  - numba=0.58
  - llvmlite=0.41
  - imagej=0.3
  - pyimagej=1.5.0
  - xarray=2023.1
  - pillow=10.4
  - tqdm=4.67
  - psutil=6.1
  - networkx=3.1
  - tifffile=2023.7.10
  - packaging=24.2
  - pip
  - pip:
    - argparse==1.4.0
    - contourpy==1.1.1
    - cycler==0.12.1
    - fonttools==4.55.0
    - imageio==2.35.1
    - imglyb==2.1.0
    - importlib-metadata==8.5.0
    - importlib-resources==6.4.5
    - jgo==1.0.6
    - jpype1==1.5.1
    - kiwisolver==1.4.7
    - labeling==0.1.14
    - lazy-loader==0.4
    - numba-progress==1.1.0
    - pyparsing==3.1.4
    - python-dateutil==2.9.0.post0
    - pytz==2024.2
    - pywavelets==1.4.1
    - scyjava==1.10.0
    - six==1.16.0
    - tzdata==2024.2
    - zipp==3.20.2
