[build-system]
requires = ["setuptools>=68,<81", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "uma-functional-assay"
version = "0.5.0"
description = "Stitching, cell measurements, and plate reports in UMA"
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = ["uma-tools>=0.2.21,<0.3"]

[project.scripts]
uma_stitching = "functional_assay.stitching:main"
uma_cell_count = "functional_assay.cell_analysis:main"
uma_functional_report = "functional_assay.functional_report:main"
uma_survival_report = "functional_assay.survival_report:main"

[tool.setuptools]
packages = ["functional_assay"]
package-dir = {functional_assay = "."}
