name: Lint and Format

on:
  push:
    branches: [main, UMA-tools-V2]
  pull_request:
    branches: [main, UMA-tools-V2]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Ruff
      uses: astral-sh/ruff-action@v3
      